platform :ios, '10.0'
use_frameworks!

target 'saltedge-ios_Example' do
  pod 'SaltEdge-iOS-Swift', :path => '../'
  pod 'PKHUD', '~> 5.0'
  pod 'SDWebImage', '~> 5.0'
  pod 'SDWebImageSVGKitPlugin'

  target 'saltedge-ios_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.3.2'
    pod 'Nimble', '~> 7.3.1'
  end
end
