platform :ios, '10.0'
use_frameworks!

target 'saltedge-ios_Example' do
  pod 'SaltEdge-iOS-Swift', :path => '../'
  pod 'PKHUD', '~> 5.0'
  pod 'SDWebImage', '~> 5.0'
  pod 'SDWebImageSVGKitPlugin'
end

target 'saltedge-ios_Tests' do
  inherit! :search_paths
  pod 'SaltEdge-iOS-Swift', :path => '../'
  pod 'Quick'
  pod 'Nimble'
end

post_install do |pi|
    pi.pods_project.targets.each do |t|
      t.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
      end
    end
end
