platform :ios, '10.0'
use_frameworks!

target 'saltedge-ios_Example' do
  pod 'SaltEdge-iOS-Swift', :path => '../'
  pod 'PKHUD', '~> 5.0'

  target 'saltedge-ios_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.3.2'
    pod 'Nimble', '~> 7.3.1'
  end
end

post_install do |installer|
   installer.pods_project.targets.each do |target|
      unless target.name == 'Nimble'
        target.build_configurations.each do |config|
          config.build_settings['SWIFT_VERSION'] = '4.0'
        end
      end
   end
end
